# site settings
title: Train
subtitle: with Adri
email: train@trainwithadri.com
description: Wanna try? Join Train With Adri and let's get to it!
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Adriana Tirnacop
gym_name: The Gym Group Southampton East
street_address: Antelope Park
line_2: Bursledon Road
city: Southampton
state: Hampshire
post_code: SO19 8NE
country: United Kingdom
# phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  # GitHub:
  # GitLab:
  # Google-Plus:
  Instagram: https://www.instagram.com/adriannaaxx/
  # LinkedIn: https://
  # Twitter:
  Facebook: https://www.facebook.com/people/Train-With-Adri-Personal-Training/61555483937230/
  # Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
  - "*.gemspec"
  - LICENSE.md
  - CONTRIBUTING.md
  - README.md
  - TODO.md
  - docker-compose.yml
  - vendor
  - justfile
  - img_raw
  - .liquidrcq
